---

- hosts: all
  become: yes
  tasks:
  - name: Create multiple files
    file: 
      path: /etc/Workshop"{{ item }}"
      state: touch
    with_items:
    - test01.txt
    - test02.txt
    - test03.txt
    - test04.txt
